### ISSUE TITLE
Cannot find the package on nuget

### ISSUE THREAD

**Issue by albertwoo** [Titaye/Fable.PolyglotProvider#11]
Can you please publish this package on nuget.org? It looks very promising and useful.

Thanks :)

**Comment by Titaye** [comment]
Hello,

The package is already available on nuget :
https://www.nuget.org/packages/Fable.PolyglotProvider/

Thierry

Le jeu. 11 mars 2021 à 08:15, slaveoftime ***@***.***> a
écrit :

**Comment by albertwoo** [comment]
Sorry my bad.
