### ISSUE TITLE
No compiled representation for provided namespace

### ISSUE THREAD

**Issue by skamlet** [Titaye/Fable.PolyglotProvider#35]
After trying to migrate a SAFE Stack project from .NET 5 to .NET 6, it seems I get some errors linked to PolyglotProvider.
```
FSC : error FS0192: erreur interne : No compiled representation for provided namespace [C:\Users\username>\source\repos\safetemp\src\Shared\Shared.fsproj]
```
I fear that some changes where made between F# 5 and F# 6/7, do you maybe know how to fix this @Titaye?
I would be happy to try to solve this, but for the moment I have no experience in type providers 😅...

**Comment by Titaye** [comment]
Hi @skamlet, Do you still have the issue with the latest version ? (Thx for the PR)

**Comment by skamlet** [comment]
Yes, everything is fine now, actually the issue was related to the way I was using the Generator.
```F#
using Fable.PolyglotProvider // <-- declaring the namespace

[<Literal>]
let path =__SOURCE_DIRECTORY__ + "/strings.en.json"
type I18n = Generator<path>
```

replacing it by the following code worked beter:
```F#
[<Literal>]
let path =__SOURCE_DIRECTORY__ + "/strings.en.json"
type I18n = Fable.PolyglotProvider.Generator<path>
```

In the end we shouldn't declare the Fable.PolyglotProvider namespace when using it .
